import pandas as pd

religious_fanatic_groups = religious_fanatic_groups = [
    "Abdullah Azzam Brigades",
    "Abu Sayyaf Group (ASG)",
    "Adan-Abyan Province of the Islamic State",
    "Ahrar Al-Jalil (Free People of the Galilee)",
    "Ahrar al-Sham",
    "Al-Aqsa Martyrs Brigade",
    "Al-Arifeen",
    "Al-Bayda Province of the Islamic State",
    "Al-Gama'at al-Islamiyya (IG)",
    "Al-Haramayn Brigades",
    "Al-Mansoorian",
    "Al-Mua'qi'oon Biddam Brigade (Those who Sign with Blood)",
    "Al-Nusrah Front",
    "Al-Qaida",
    "Al-Qaida in Iraq",
    "Al-Qaida in Saudi Arabia",
    "Al-Qaida in the Arabian Peninsula (AQAP)",
    "Al-Qaida in the Islamic Maghreb (AQIM)",
    "Al-Qaida in Yemen",
    "Al-Qaida Kurdish Battalions (AQKB)",
    "Al-Shuda Brigade",
    "Al-Shabaab",
    "Algeria Province of the Islamic State",
    "Algerian Islamic Extremists",
    "Ansar Allah",
    "Ansar Bayt al-Maqdis (Ansar Jerusalem)",
    "Ansar al-Dine (Mali)",
    "Ansar al-Islam",
    "Ansar al-Sharia (Libya)",
    "Ansar al-Sharia (Tunisia)",
    "Ansarul Islam (Pakistan)",
    "Armed Islamic Group (GIA)",
    "Armed Vanguards of a Second Mohammed Army",
    "Army of Islam",
    "Asa'ib Ahl al-Haqq",
    "Bahrain Province of the Islamic State",
    "Barqa Province of the Islamic State",
    "Boko Haram",
    "Caucasus Emirate",
    "Caucasus Province of the Islamic State",
    "Chechen Rebels",
    "Deccan Mujahideen",
    "Eastern Turkistan Islamic Movement (ETIM)",
    "Egyptian Islamic Jihad (Al-Jihad)",
    "Fezzan Province of the Islamic State",
    "Gathering to Aid the Oppressed",
    "Great Eastern Islamic Raiders Front (IBDA-C)",
    "Hadramawt Province of the Islamic State",
    "Hamas (Islamic Resistance Movement)",
    "Harkatul Jihad-e-Islami",
    "Harakat Ansar Iran (HAI)",
    "Haqqani Network",
    "Hay'at Tahrir al-Sham",
    "Hezbollah",
    "Hijaz Province of the Islamic State",
    "Hizb-I-Islami",
    "Hizbul Mujahideen (HM)",
    "Houthi extremists (Ansar Allah)",
    "Imam Shamil Battalion",
    "Iraqi Sunni Extremists",
    "Iraqi extremists",
    "Islamic Army in Iraq (al-Jaish al-Islami fi al-Iraq)",
    "Islamic Front",
    "Islamic Front (Syria)",
    "Islamic Jihad Group (IJG)",
    "Islamic Jihad Union (Uzbekistan)",
    "Islamic Movement of Uzbekistan (IMU)",
    "Islamic State in Bangladesh",
    "Islamic State in Egypt",
    "Islamic State in the Greater Sahara (ISGS)",
    "Islamic State of Iraq (ISI)",
    "Islamic State of Iraq and the Levant (ISIL)",
    "Islamic State in Egypt",
    "Islamic State in the Greater Sahara (ISGS)",
    "Islamic State of Iraq and the Levant (ISIL)",
    "Islamic State of Iraq (ISI)",
    "Islamic State in Bangladesh",
    "Islamic State in Egypt",
    "Islamic State in the Greater Sahara (ISGS)",
    "Islambouli Brigades of al-Qaida",
    "Jabha East Africa",
    "Jaish Tahkim al-Din",
    "Jaish-e-Islam",
    "Jaish-e-Mohammad (JeM)",
    "Jama'atul Mujahideen Bangladesh (JMB)",
    "Jamaah Ansharut Daulah",
    "Jamaah Ansharut Tauhid (JAT)",
    "Jamaat-E-Islami (Bangladesh)",
    "Jamaat-ul-Ahrar",
    "Jaysh al-Islam (Syria)",
    "Jemaah Islamiya (JI)",
    "Jihadi-inspired extremists",
    "Jund al-Aqsa",
    "Jund al-Khilafah (Tunisia)",
    "Jund al-Sham for Tawhid and Jihad",
    "Jundallah (Iran)",
    "Jundallah (Pakistan)",
    "Karabulak Gang",
    "Khalid ibn Walid",
    "Khorasan Chapter of the Islamic State",
    "Lashkar-e-Islam (Pakistan)",
    "Lashkar-e-Jhangvi",
    "Lashkar-e-Omar",
    "Lashkar-e-Taiba (LeT)",
    "Liberation Tigers of Tamil Eelam (LTTE)",
    "Liwa Ahrar al-Sunna",
    "Moroccan extremists",
    "Movement for Oneness and Jihad in West Africa (MUJAO)",
    "Mujahideen Ansar",
    "Mujahideen Shura Council",
    "Mujahidin Indonesia Timur (MIT)",
    "Mujahideen Youth Movement (MYM)",
    "Mullah Dadullah Front",
    "Muslim Rebels",
    "Muslim extremists",
    "Najd Province of the Islamic State",
    "Nur-al-Din al-Zinki Movement",
    "Organization of Soldiers of the Levant",
    "Palestinian Extremists",
    "Palestinian Islamic Jihad (PIJ)",
    "Qari Kamran Group",
    "Riyadus-Salikhin Reconnaissance and Sabotage Battalion of Chechen Martyrs",
    "Salafia Jihadia",
    "Sanaa Province of the Islamic State",
    "Shamiya Front",
    "Shura Council of Benghazi Revolutionaries",
    "Sinai Province of the Islamic State",
    "Sunni Muslim extremists",
    "Sunni Supporters",
    "Tajamo Ansar al-Islam",
    "Taliban",
    "Taliban (Pakistan)",
    "Tawhid and Jihad",
    "Tehrik-e-Khilafat",
    "Tehrik-e-Taliban Islami (TTI)",
    "Tehrik-i-Taliban Pakistan (TTP)",
    "Tripoli Province of the Islamic State",
    "Turkestan Islamic Party",
    "Uighur Separatists",
    "Unification Army Sons Brigade",
    "United Jihad Council"
]

cols = 'eventid,iyear,imonth,iday,country_txt,region_txt,provstate,city,attacktype1_txt,attacktype2_txt,attacktype3_txt,targtype1_txt,target1,gname,weaptype1_txt,weaptype2_txt,weapsubtype1_txt,nkill,nwound,property,propvalue,propcomment,motive,summary,success,suicide,claimed,claimmode_txt,ransom,ransomamt,hostkidoutcome_txt,latitude,longitude'
cols = cols.split(',')

df = pd.read_csv('gtd.csv')
df = df[cols]

df['religious_fanatic_group'] = ""

mask_unknown = df['gname'].isna() | (df['gname'] == '') | (df['gname'] == 'Unknown')
mask_in_list = df['gname'].isin(religious_fanatic_groups)
mask_not_in_list = ~df['gname'].isin(religious_fanatic_groups) & ~mask_unknown

df.loc[mask_in_list, 'religious_fanatic_group'] = 1
df.loc[mask_not_in_list, 'religious_fanatic_group'] = 0

df.to_csv('gtd_filtered.csv', index=False)
